import { useCallback, useEffect, useRef, useState, useSyncExternalStore } from 'react';
import { Button } from '../design-system';
import { playSound } from '../services/sound';
import { startBgm, stopBgm, isBgmOn } from '../services/bgm';
import type { BgmTrack } from '../services/bgm';
import {
  EFFECTS_REGISTRY,
  weightedRandomEffectTutorial,
  pickGuaranteedRareOrEpic,
  getRandomThemeLimitedEffectKey,
} from '../data/effectsRegistry';
import { runVanillaCompletionEffect, playDemoEffect } from '../services/taskAnimations';
import { DemoTaskItem } from './CollectionPage/DemoTaskItem';
import { ThemeHomePreview } from './CollectionPage/ThemeHomePreview';
import { PacmanProgress } from '../components/PacmanProgress';
import { themeList } from '../design-system/themes/themeRegistry';
import type { CSSProperties } from 'react';
import type { Lang } from '../lib/i18n';
import './LandingPage.css';

interface LandingPageProps {
  lang: 'en' | 'ja';
  onChangeLang: (l: 'en' | 'ja') => void;
  onOpenLogin: () => void;
  onOpenSignup: () => void;
}

/* ── Mobile auto-play helpers ─────────────────────────────────────── */

/**
 * Returns true on touch-primary devices (no fine pointer). Used to decide
 * whether a card should auto-activate on scroll-into-view instead of
 * relying on hover.
 */
function useCoarsePointer(): boolean {
  const subscribe = (cb: () => void) => {
    if (typeof window === 'undefined') return () => {};
    const mq = window.matchMedia('(pointer: coarse)');
    mq.addEventListener?.('change', cb);
    return () => mq.removeEventListener?.('change', cb);
  };
  return useSyncExternalStore(
    subscribe,
    () => typeof window !== 'undefined' && window.matchMedia('(pointer: coarse)').matches,
    () => false,
  );
}

/**
 * Returns true while the element is intersecting the viewport by at least
 * `threshold`. Used to auto-activate feature cards on mobile during scroll.
 */
function useInView(ref: React.RefObject<HTMLElement | null>, threshold = 0.5): boolean {
  const [inView, setInView] = useState(false);
  useEffect(() => {
    const el = ref.current;
    if (!el || typeof IntersectionObserver === 'undefined') return;
    const obs = new IntersectionObserver(
      ([entry]) => setInView(entry.isIntersecting && entry.intersectionRatio >= threshold),
      { threshold },
    );
    obs.observe(el);
    return () => obs.disconnect();
  }, [ref, threshold]);
  return inView;
}

/* ── Smash & Reward card ───────────────────────────────────────────── */

/**
 * Smash & Reward feature card — hover reveals a scattered burst of
 * pre-captured effect-peak screenshots (generated by
 * `npm run capture-effects`, stored in public/effect-shots/*.png).
 * No sound, no runtime effect engine — fully static visuals.
 * On mobile (coarse pointer), the card auto-activates while in viewport.
 */
// Excluded: bomb / freeze / owlBlink / neonBigBang / rainbowSmash / neonWarp
// — these repaint the background or look weird as static stills on a card.
const SMASH_CARD_SHOT_POOL = [
  'fighter_punch', 'butterflyFly',
  'giantTreeGrow', 'fireflyBurst', 'chomp',
  'laserCutter', 'scanDrone', 'leafScatter', 'glitchSlide',
] as const;

const SMASH_CARD_SHOT_SLOTS: Array<{ top: string; left: string; size: number; rotate: number; delay: number }> = [
  { top: '-6%',  left: '-14%', size: 260, rotate:  -9, delay:   0 },
  { top: '-14%', left: '30%',  size: 280, rotate:  10, delay:  90 },
  { top: '-2%',  left: '62%',  size: 240, rotate: -12, delay: 180 },
];

function pickRandomShots(count: number): string[] {
  const pool = [...SMASH_CARD_SHOT_POOL];
  const out: string[] = [];
  for (let i = 0; i < count && pool.length > 0; i++) {
    const idx = Math.floor(Math.random() * pool.length);
    out.push(pool[idx]);
    pool.splice(idx, 1);
  }
  return out;
}

function SmashRewardCard({ lang }: { lang: Lang }) {
  const isJa = lang === 'ja';
  const cardRef = useRef<HTMLElement>(null);
  const isCoarse = useCoarsePointer();
  const inView = useInView(cardRef);
  const [hovering, setHovering] = useState(false);
  const [shots, setShots] = useState<string[]>(() => pickRandomShots(SMASH_CARD_SHOT_SLOTS.length));

  const isActive = hovering || (isCoarse && inView);

  // Reshuffle shots whenever we transition into active (hover on desktop,
  // scroll-into-view on mobile) so each reveal shows new art.
  useEffect(() => {
    if (isActive) setShots(pickRandomShots(SMASH_CARD_SHOT_SLOTS.length));
  }, [isActive]);

  return (
    <article
      ref={cardRef}
      className={`lp-feature-card lp-feature-card--interactive${isActive ? ' is-active' : ''}`}
      onMouseEnter={() => setHovering(true)}
      onMouseLeave={() => setHovering(false)}
    >
      <span className="lp-feature-card__num">01</span>
      <h3 className="lp-feature-card__title">
        {isJa ? 'スマッシュして報酬' : 'Smash & Reward'}
      </h3>
      <ul className="lp-feature-card__list">
        <li>{isJa ? 'タスク完了ごとにピクセルアートの演出が発動' : 'Every completed task triggers a pixel-art effect'}</li>
        <li>{isJa ? 'Common / Rare / Epic — 常にランダム' : 'Common, Rare, or Epic — always random'}</li>
        <li>{isJa ? '無限に消せるSmash Listで、ストレス発散' : 'Smash List — unlimited, stress-busting tasks'}</li>
      </ul>
      <div className="lp-feature-card__accent lp-smash-burst" aria-hidden="true">
        {SMASH_CARD_SHOT_SLOTS.map((slot, i) => {
          const key = shots[i];
          if (!key) return null;
          return (
            <img
              key={`${key}-${i}`}
              src={`/effect-shots/${key}.png`}
              alt=""
              className="lp-smash-shot"
              draggable={false}
              style={{
                top: slot.top,
                left: slot.left,
                width: slot.size,
                ['--lp-shot-rot' as string]: `${slot.rotate}deg`,
                animationDelay: `${slot.delay}ms`,
                transitionDelay: `${slot.delay}ms`,
              }}
            />
          );
        })}
      </div>
    </article>
  );
}

/**
 * Your World feature card — hover-driven theme cycle demo.
 * Applies each theme's CSS variable overrides directly to the card root,
 * so the entire card's accent/background/text reskins as it cycles through
 * arcade → synthwave → forestbit every 2s.
 */
function YourWorldCard({ lang }: { lang: Lang }) {
  const isJa = lang === 'ja';
  const cardRef = useRef<HTMLElement>(null);
  const isCoarse = useCoarsePointer();
  const inView = useInView(cardRef);
  const [hovering, setHovering] = useState(false);
  const [idx, setIdx] = useState(0);

  const isActive = hovering || (isCoarse && inView);

  useEffect(() => {
    if (!isActive) {
      setIdx(0);
      return;
    }
    setIdx((i) => (i + 1) % themeList.length);
    const id = window.setInterval(() => {
      setIdx((i) => (i + 1) % themeList.length);
    }, 2000);
    return () => window.clearInterval(id);
  }, [isActive]);

  const theme = themeList[idx];
  const previewVars = (theme.cssVariables.dark
    ?? theme.cssVariables.light
    ?? {}) as CSSProperties;
  const bgOverride =
    theme.cssVariables.dark?.['--pd-color-background-default']
    ?? theme.cssVariables.light?.['--pd-color-background-default'];

  const cardStyle: CSSProperties = isActive
    ? { ...previewVars, ...(bgOverride ? { background: bgOverride } : {}) }
    : {};

  return (
    <article
      ref={cardRef}
      className={`lp-feature-card lp-feature-card--interactive lp-feature-card--theme${isActive ? ' is-active' : ''}`}
      style={cardStyle}
      onMouseEnter={() => setHovering(true)}
      onMouseLeave={() => setHovering(false)}
    >
      <span className="lp-feature-card__num">03</span>
      <h3 className="lp-feature-card__title">
        {isJa ? '自分だけの世界' : 'Your World'}
      </h3>
      <ul className="lp-feature-card__list">
        <li>{isJa ? '世界観・音・エフェクトが丸ごと変わるテーマ' : 'Choose a theme that changes everything — visuals, sounds, effects'}</li>
        <li>{isJa ? 'タスクを終わらせるほど、テーマが育つ (近日実装)' : 'Themes grow as you complete tasks (coming soon)'}</li>
        <li>{isJa ? '月替わりチャレンジで限定エフェクトを獲得' : 'Earn limited effects through monthly challenges'}</li>
      </ul>
      <div className="lp-feature-card__accent lp-your-world">
        <span className="lp-your-world__icon" aria-hidden="true">{theme.icon}</span>
        <span className="lp-your-world__name">{theme.name}</span>
      </div>
    </article>
  );
}

/**
 * Stay Focused feature card — hover-driven Pomodoro demo.
 * On mouse enter: plays the app's existing retro chiptune via startBgm('retro')
 * and counts down a mini CRT-style timer display from 25:00.
 * On mouse leave: stops BGM and resets.
 * At 0:00: plays the pomodoro-complete fanfare and stops.
 */
const LP_BGM_TRACKS: BgmTrack[] = ['retro', 'synthwave', 'chill', 'nightCity', 'rain', 'fireplace'];

function StayFocusedCard({ isJa }: { isJa: boolean }) {
  const TOTAL = 25 * 60;
  // Mobile auto-play runs for a short teaser only so BGM doesn't linger
  // while the user scrolls past or reads the rest of the page.
  const MOBILE_AUTOPLAY_MS = 6000;

  const cardRef = useRef<HTMLElement>(null);
  const isCoarse = useCoarsePointer();
  const inView = useInView(cardRef);
  const [seconds, setSeconds] = useState(TOTAL);
  const [hovering, setHovering] = useState(false);
  const [mobileAutoActive, setMobileAutoActive] = useState(false);
  const bgmStartedRef = useRef(false);
  const bgmIdxRef = useRef(0);

  // Mobile: run a capped teaser when the card scrolls into view.
  useEffect(() => {
    if (!isCoarse) return;
    if (!inView) {
      setMobileAutoActive(false);
      return;
    }
    setMobileAutoActive(true);
    const stopId = window.setTimeout(() => setMobileAutoActive(false), MOBILE_AUTOPLAY_MS);
    return () => window.clearTimeout(stopId);
  }, [isCoarse, inView]);

  const isActive = hovering || mobileAutoActive;

  useEffect(() => {
    if (!isActive) {
      if (bgmStartedRef.current) {
        stopBgm();
        bgmStartedRef.current = false;
      }
      setSeconds(TOTAL);
      return;
    }
    if (isBgmOn()) {
      const track = LP_BGM_TRACKS[bgmIdxRef.current % LP_BGM_TRACKS.length];
      bgmIdxRef.current = (bgmIdxRef.current + 1) % LP_BGM_TRACKS.length;
      startBgm(track);
      bgmStartedRef.current = true;
    }
    const id = window.setInterval(() => {
      setSeconds((s) => Math.max(0, s - 1));
    }, 1000);
    return () => window.clearInterval(id);
  }, [isActive]);

  useEffect(() => {
    if (isActive && seconds === 0) {
      playSound('focusPomodoroComplete');
      setHovering(false);
      setMobileAutoActive(false);
    }
  }, [seconds, isActive]);

  // Unmount safety — never leak BGM beyond the LP card lifetime.
  useEffect(() => () => {
    if (bgmStartedRef.current) {
      stopBgm();
      bgmStartedRef.current = false;
    }
  }, []);

  const mm = String(Math.floor(seconds / 60)).padStart(2, '0');
  const ss = String(seconds % 60).padStart(2, '0');

  return (
    <article
      ref={cardRef}
      className={`lp-feature-card lp-feature-card--interactive${isActive ? ' is-active' : ''}`}
      onMouseEnter={() => setHovering(true)}
      onMouseLeave={() => setHovering(false)}
    >
      <span className="lp-feature-card__num">02</span>
      <h3 className="lp-feature-card__title">
        {isJa ? '楽しく、捗る。' : 'Stay Focused'}
      </h3>
      <ul className="lp-feature-card__list">
        <li>{isJa ? 'ポモドーロ・タイマー内蔵' : 'Built-in Pomodoro timer'}</li>
        <li>{isJa ? 'シンプルなタスクリスト — 余計な機能なし' : 'Simple task lists — no clutter, no complexity'}</li>
        <li>{isJa ? '毎日・毎週の習慣づくりに繰り返しタスク' : 'Repeat tasks for daily and weekly habits'}</li>
      </ul>
      <div className="lp-focus-demo">
        <div className="lp-focus-demo__digits">{mm}:{ss}</div>
        <PacmanProgress
          remaining={seconds}
          totalSeconds={TOTAL}
          timerState={hovering ? 'running' : 'idle'}
        />
      </div>
    </article>
  );
}

const HERO_EFFECT_OBJECTS = [
  { src: '/fighter-punch.gif', alt: 'Punch' },
  { src: '/bomb.gif', alt: 'Bomb' },
  { src: '/sprites/scan-drone.gif', alt: 'Scan drone' },
];

export function LandingPage({ lang, onChangeLang, onOpenLogin, onOpenSignup }: LandingPageProps) {
  const isJa = lang === 'ja';

  const taskRef = useRef<HTMLDivElement>(null);

  useEffect(() => () => {
    const el = taskRef.current;
    if (el) el.style.visibility = '';
  }, []);

  const handleSmash = useCallback(() => {
    const el = taskRef.current;
    if (!el) return;
    // Clear any leftover hidden state from a prior in-flight effect so a rapid
    // follow-up smash can start on a visible element and render its own clone.
    el.style.visibility = '';
    playSound('taskComplete');

    // LP hero shows the full catalog (every theme's Rare/Epic + challenge effects),
    // biased heavily toward Rare/Epic for first-impression wow.
    const pool = EFFECTS_REGISTRY;
    const chosen = Math.random() < 0.8
      ? pickGuaranteedRareOrEpic(pool)
      : weightedRandomEffectTutorial(pool);

    runVanillaCompletionEffect(el, () => {}, chosen.key);
  }, []);

  const handleLogin = useCallback(() => {
    playSound('buttonClick');
    onOpenLogin();
  }, [onOpenLogin]);

  const handleSignup = useCallback(() => {
    playSound('buttonClick');
    onOpenSignup();
  }, [onOpenSignup]);

  const handleLangToggle = useCallback((l: 'en' | 'ja') => {
    playSound('buttonClick');
    onChangeLang(l);
  }, [onChangeLang]);

  return (
    <div className="lp-root">
      {/* ─── LP Header (sticky, full-width) ───────────────────── */}
      <header className="lp-header">
        <div className="lp-header__brand">
          <img src="/pixdone-symbol-bland.svg" alt="PixDone" className="lp-header__logo" />
        </div>
        <div className="lp-header__actions">
          <div className="lp-header__lang">
            <button
              type="button"
              className={`lp-lang-chip${lang === 'en' ? ' is-active' : ''}`}
              onClick={() => handleLangToggle('en')}
            >
              EN
            </button>
            <button
              type="button"
              className={`lp-lang-chip${lang === 'ja' ? ' is-active' : ''}`}
              onClick={() => handleLangToggle('ja')}
            >
              JA
            </button>
          </div>
          <Button variant="ghost" size="sm" onClick={handleLogin}>
            {isJa ? 'ログイン' : 'Log in'}
          </Button>
          <Button variant="primary" size="sm" onClick={handleSignup}>
            {isJa ? '新規登録' : 'Sign up'}
          </Button>
        </div>
      </header>

      {/* ─── Hero ───────────────────────────────────────────────── */}
      <section className="lp-section lp-section--hero">
        <div className="lp-container">
          <div className="lp-hero">
            <div className="lp-hero-left">
              <div className="lp-effect-objects" aria-hidden="true">
                {HERO_EFFECT_OBJECTS.map((obj) => (
                  <img
                    key={obj.src}
                    src={obj.src}
                    alt={obj.alt}
                    className="lp-effect-objects__item"
                    draggable={false}
                  />
                ))}
              </div>

              <div className="lp-hero-task">
                <DemoTaskItem
                  ref={taskRef}
                  lang={lang}
                  onSmash={handleSmash}
                />
                <div className="lp-smash-hint" aria-hidden="true">
                  <span className="lp-smash-hint__arrow">↑</span>
                  <span className="lp-smash-hint__label">
                    {isJa ? 'タップしてスマッシュ！' : 'Smash me!'}
                  </span>
                </div>
              </div>
            </div>

            <div className="lp-hero-right">
              <h1 className="lp-headline">
                {isJa ? (
                  <>
                    「終わった」を<br />
                    <span style={{ whiteSpace: 'nowrap' }}>
                      <span className="lp-accent">一番気持ちいい</span>瞬間に。
                    </span>
                  </>
                ) : (
                  <>
                    Make finishing tasks the <span className="lp-accent">best part</span> of your day.
                  </>
                )}
              </h1>
              <p className="lp-subcopy">
                {isJa
                  ? 'タスクを完了するたびに、ランダムなピクセルアートの報酬が飛び出す。'
                  : 'Random pixel rewards every time you complete a task.'}
              </p>
              <div className="lp-cta-row">
                <Button variant="primary" size="lg" onClick={handleSignup}>
                  {isJa ? '無料で始める →' : 'Start for free →'}
                </Button>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ─── Why PixDone? ──────────────────────────────────────── */}
      <section className="lp-section lp-section--alt">
        <div className="lp-container">
          <div className="lp-features">
            <SmashRewardCard lang={lang} />
            <StayFocusedCard isJa={isJa} />
            <YourWorldCard lang={lang} />
          </div>
        </div>
      </section>

      {/* ─── Theme Showcase ───────────────────────────────────── */}
      <section className="lp-section">
        <div className="lp-container">
          <div className="lp-themes-head">
            <h2 className="lp-h2">
              {isJa ? '世界を選ぼう' : 'Pick your world'}
            </h2>
            <p className="lp-h2-sub">
              {isJa ? 'テーマは続々追加予定。' : 'New worlds dropping all the time.'}
            </p>
          </div>
          <div className="lp-theme-grid">
            {themeList.map((theme) => {
              const previewVars = (theme.cssVariables.dark
                ?? theme.cssVariables.light
                ?? {}) as CSSProperties;
              const bgColor =
                (theme.cssVariables.dark?.['--pd-color-background-default'])
                ?? (theme.cssVariables.light?.['--pd-color-background-default'])
                ?? 'var(--pd-color-background-default)';
              return (
                <div className="lp-theme-preview" key={theme.key}>
                  <div
                    className="lp-theme-preview__stage"
                    style={{ ...previewVars, background: bgColor }}
                  >
                    <ThemeHomePreview
                      lang={lang}
                      onTriggerEffect={(taskEl) => {
                        playSound('buttonClick');
                        playDemoEffect(getRandomThemeLimitedEffectKey(theme.key), taskEl);
                      }}
                    />
                  </div>
                  <div className="lp-theme-preview__foot">
                    <span className="lp-theme-preview__name">
                      <span aria-hidden="true">{theme.icon}</span> {theme.name}
                    </span>
                  </div>
                </div>
              );
            })}
          </div>
          <p className="lp-theme-more">
            {isJa ? '✨ もっと続々追加予定…' : '✨ More worlds coming…'}
          </p>
        </div>
      </section>

      {/* ─── Pricing ──────────────────────────────────────────── */}
      <section className="lp-section lp-section--alt">
        <div className="lp-container">
          <div className="lp-themes-head">
            <h2 className="lp-h2">
              {isJa ? 'シンプルな料金' : 'Simple pricing'}
            </h2>
            <p className="lp-h2-sub">
              {isJa ? '無料で始めて、必要になったら PixDone+' : 'Start free. Upgrade when you need it.'}
            </p>
          </div>

          <div className="lp-pricing-grid">
            <article className="lp-pricing-card">
              <h3 className="lp-pricing-card__tier">FREE</h3>
              <p className="lp-pricing-card__price">¥0</p>
              <ul className="lp-pricing-card__list">
                <li>{isJa ? 'Smash List 無制限' : 'Unlimited Smash List'}</li>
                <li>{isJa ? 'タスクリスト 3 件まで' : 'Up to 3 task lists'}</li>
                <li>{isJa ? 'Common エフェクト' : 'Common effects'}</li>
                <li>{isJa ? '月替わりチャレンジ (期間中)' : 'Monthly challenge effects (during event)'}</li>
                <li>{isJa ? 'デフォルトテーマ (Arcade)' : 'Default theme (Arcade)'}</li>
              </ul>
              <Button variant="secondary" size="lg" onClick={handleSignup}>
                {isJa ? '無料で始める' : 'Start free'}
              </Button>
            </article>

            <article className="lp-pricing-card lp-pricing-card--plus">
              <h3 className="lp-pricing-card__tier">PIXDONE+</h3>
              <p className="lp-pricing-card__price">
                ¥600<small>{isJa ? '/月' : '/MO'}</small>
              </p>
              <ul className="lp-pricing-card__list">
                <li>{isJa ? '無制限のタスクリスト' : 'Unlimited task lists'}</li>
                <li>{isJa ? '全プリセットテーマ + 進化' : 'All preset themes + progression'}</li>
                <li>{isJa ? 'Rare + Epic エフェクト' : 'Rare + Epic effects'}</li>
                <li>{isJa ? 'エフェクトリクエスト (月1回)' : 'Monthly effect request'}</li>
                <li>{isJa ? '年払いなら ¥6,000 (2ヶ月分おトク)' : '¥6,000 / year (2 months free)'}</li>
              </ul>
              <Button variant="primary" size="lg" onClick={handleSignup}>
                {isJa ? 'PixDone+ を始める' : 'Get PixDone+'}
              </Button>
            </article>
          </div>
          <p className="lp-pricing-foot">
            {isJa ? 'いつでもキャンセル可 · 7日以内なら返金可能' : 'Cancel anytime · Refund within 7 days'}
          </p>
        </div>
      </section>

      {/* ─── Final CTA ────────────────────────────────────────── */}
      <section className="lp-section lp-section--final">
        <div className="lp-container lp-final">
          <div className="lp-final__left">
            <img
              src="/lp-screenshots.png"
              alt={isJa ? 'PixDone のデスクトップとモバイル画面' : 'PixDone desktop and mobile screens'}
              className="lp-final__shot"
            />
          </div>
          <div className="lp-final__right">
            <h2 className="lp-final__headline">
              {isJa ? '気持ちいいだけで、毎日がこんなに捗る。' : "Your to-do list has never felt this good."}
            </h2>
            {isJa && (
              <p className="lp-subcopy">
                終わりが気持ちいい毎日、始めよう。
              </p>
            )}
            <Button variant="primary" size="lg" onClick={handleSignup}>
              {isJa ? '無料で始める →' : 'Start for free →'}
            </Button>
          </div>
        </div>
      </section>

      {/* ─── Footer ───────────────────────────────────────────── */}
      <footer className="lp-footer">
        <div className="lp-container lp-footer__inner">
          <img src="/pixdone-symbol-bland.svg" alt="PixDone" className="lp-footer__logo" />
          <div className="lp-footer__links">
            <a href="/privacy.html" target="_blank" rel="noopener noreferrer">Privacy</a>
            <a href="/terms.html" target="_blank" rel="noopener noreferrer">Terms</a>
            <a href="mailto:pixdone@akizony.com">Support</a>
          </div>
          <a
            href="https://www.producthunt.com/products/pixdone-todo-app-with-pixel-effects?embed=true&utm_source=badge-featured&utm_medium=badge&utm_campaign=badge-pixdone"
            target="_blank"
            rel="noopener noreferrer"
            className="lp-footer__ph"
          >
            <img
              src="https://api.producthunt.com/widgets/embed-image/v1/featured.svg?post_id=1119592&theme=light&t=1776156649500"
              alt="PixDone - Earn random pixel rewards every time you smash a task | Product Hunt"
              width={250}
              height={54}
            />
          </a>
          <span>© 2026 PixDone</span>
        </div>
      </footer>
    </div>
  );
}
