/**
 * AUTO-GENERATED — do not edit by hand.
 * Source of truth: design-tokens/*.json (Tokens Studio format).
 * Regenerate with `npm run tokens:build`.
 */

export const light: Record<string, string> = {
  '--pd-color-surface-page': 'var(--pd-fb-sky-50)',
  '--pd-color-surface-page-alt': 'var(--pd-fb-sky-100)',
  '--pd-color-surface-primary': 'var(--pd-fb-sky-200)',
  '--pd-color-surface-secondary': 'var(--pd-fb-sky-50)',
  '--pd-color-surface-raised': 'var(--pd-fb-moss-100)',
  '--pd-color-surface-overlay': 'color-mix(in srgb, var(--pd-fb-bark-900) 65%, transparent)',
  '--pd-color-surface-inverse': 'var(--pd-fb-bark-900)',
  '--pd-color-surface-disabled': 'var(--pd-fb-sky-200)',
  '--pd-color-text-primary': 'var(--pd-fb-bark-900)',
  '--pd-color-text-secondary': 'var(--pd-fb-bark-700)',
  '--pd-color-text-tertiary': 'var(--pd-fb-bark-500)',
  '--pd-color-text-inverse': 'var(--pd-fb-sky-50)',
  '--pd-color-text-disabled': 'var(--pd-fb-bark-500)',
  '--pd-color-text-accent': 'var(--pd-fb-leaf-700)',
  '--pd-color-text-success': 'var(--pd-fb-success-light)',
  '--pd-color-text-warning': 'var(--pd-fb-amber-light)',
  '--pd-color-text-danger': 'var(--pd-fb-danger-light)',
  '--pd-color-border-outline-variant': 'color-mix(in srgb, var(--pd-fb-leaf-700) 20%, transparent)',
  '--pd-color-border-outline': 'color-mix(in srgb, var(--pd-fb-leaf-700) 38%, transparent)',
  '--pd-color-border-interactive': 'var(--pd-fb-leaf-700)',
  '--pd-color-border-interactive-active': 'var(--pd-fb-leaf-900)',
  '--pd-color-border-inverse': 'var(--pd-fb-sky-50)',
  '--pd-color-border-focus': 'var(--pd-fb-leaf-700)',
  '--pd-color-border-danger': 'var(--pd-fb-danger-light)',
  '--pd-color-feedback-info': 'var(--pd-fb-leaf-700)',
  '--pd-color-feedback-success': 'var(--pd-fb-success-light)',
  '--pd-color-feedback-warning': 'var(--pd-fb-amber-light)',
  '--pd-color-feedback-danger': 'var(--pd-fb-danger-light)',
  '--pd-color-action-primary': 'var(--pd-fb-leaf-700)',
  '--pd-color-action-primary-hover': 'var(--pd-fb-leaf-900)',
  '--pd-color-action-primary-pressed': '#0f2e0f',
  '--pd-color-action-secondary': 'var(--pd-fb-sky-200)',
  '--pd-color-action-secondary-hover': 'var(--pd-fb-moss-200)',
  '--pd-color-action-secondary-pressed': 'var(--pd-fb-leaf-300)',
  '--pd-color-action-ghost-hover': 'color-mix(in srgb, var(--pd-fb-leaf-700) 10%, transparent)',
  '--pd-color-action-ghost-pressed': 'color-mix(in srgb, var(--pd-fb-leaf-700) 20%, transparent)',
  '--pd-color-action-disabled': 'var(--pd-fb-sky-200)',
  '--pd-color-focus-ring': 'color-mix(in srgb, var(--pd-fb-leaf-700) 80%, transparent)',
  '--pd-color-focus-ring-offset': 'var(--pd-fb-sky-50)',
  '--pd-fb-sky-50': '#d4f0f8',
  '--pd-fb-sky-100': '#c0e8f4',
  '--pd-fb-sky-200': '#a8ddf0',
  '--pd-fb-leaf-300': '#7acc7a',
  '--pd-fb-leaf-500': '#4aaa4a',
  '--pd-fb-leaf-700': '#2d6b2d',
  '--pd-fb-leaf-900': '#1a4219',
  '--pd-fb-sun-400': '#f9e04b',
  '--pd-fb-bark-500': '#4a6a40',
  '--pd-fb-bark-700': '#2d4a28',
  '--pd-fb-bark-900': '#1a2a18',
  '--pd-fb-moss-100': '#e8f8e8',
  '--pd-fb-moss-200': '#d0ecd0',
  '--pd-fb-danger-light': '#b03020',
  '--pd-fb-danger-light-hover': '#7a1a10',
  '--pd-fb-amber-light': '#886000',
  '--pd-fb-success-light': '#1a6a1a',
  '--pd-fb-success-light-hover': '#0f4a0f',
  '--pd-fb-smash-text-light': '#1a5a1a',
  '--pd-fb-smash-hint-light': '#3a7a3a',
  '--pd-fb-smash-grad-start-light': '#ddf8dd',
  '--pd-fb-smash-grad-end-light': '#c8f0c8',
  '--pd-color-background-default': 'var(--pd-fb-sky-50)',
  '--pd-color-background-elevated': 'var(--pd-fb-moss-100)',
  '--pd-color-background-hover': 'var(--pd-fb-moss-200)',
  '--pd-color-text-muted': 'var(--pd-fb-bark-500)',
  '--pd-color-accent-default': 'var(--pd-fb-leaf-700)',
  '--pd-color-accent-hover': 'var(--pd-fb-leaf-900)',
  '--pd-color-accent-subtle': 'color-mix(in srgb, var(--pd-fb-leaf-700) 12%, transparent)',
  '--pd-color-accent-filled': 'var(--pd-fb-leaf-700)',
  '--pd-color-accent-text': '#ffffff',
  '--pd-color-shadow-default': 'color-mix(in srgb, var(--pd-fb-leaf-700) 22%, transparent)',
  '--pd-color-semantic-success': 'var(--pd-fb-success-light)',
  '--pd-color-semantic-danger': 'var(--pd-fb-danger-light)',
  '--pd-color-semantic-warning': 'var(--pd-fb-amber-light)',
  '--pd-color-smash-border': 'var(--pd-fb-leaf-700)',
  '--pd-color-smash-text': 'var(--pd-fb-smash-text-light)',
  '--pd-color-smash-hint': 'var(--pd-fb-smash-hint-light)',
  '--pd-color-overlay-backdrop': 'color-mix(in srgb, var(--pd-fb-bark-900) 60%, transparent)',
  '--pd-effect-particle-1': '#4aaa4a',
  '--pd-effect-particle-2': '#2d6b2d',
  '--pd-effect-particle-3': '#f9e04b',
  '--pd-effect-particle-4': '#7acc7a',
};

export const dark: Record<string, string> = {
  '--pd-color-surface-page': 'var(--pd-fb-night-950)',
  '--pd-color-surface-page-alt': 'var(--pd-fb-night-900)',
  '--pd-color-surface-primary': 'var(--pd-fb-night-800)',
  '--pd-color-surface-secondary': 'var(--pd-fb-night-950)',
  '--pd-color-surface-raised': 'var(--pd-fb-night-700)',
  '--pd-color-surface-overlay': 'color-mix(in srgb, var(--pd-fb-night-950) 88%, transparent)',
  '--pd-color-surface-inverse': 'var(--pd-fb-text-50)',
  '--pd-color-surface-disabled': 'var(--pd-fb-night-600)',
  '--pd-color-text-primary': 'var(--pd-fb-text-50)',
  '--pd-color-text-secondary': 'var(--pd-fb-text-200)',
  '--pd-color-text-tertiary': 'var(--pd-fb-text-muted)',
  '--pd-color-text-inverse': 'var(--pd-fb-night-950)',
  '--pd-color-text-disabled': 'var(--pd-fb-text-muted)',
  '--pd-color-text-accent': 'var(--pd-fb-glow-300)',
  '--pd-color-text-success': 'var(--pd-fb-glow-300)',
  '--pd-color-text-warning': 'var(--pd-fb-amber-dark)',
  '--pd-color-text-danger': 'var(--pd-fb-danger-dark)',
  '--pd-color-border-outline-variant': 'color-mix(in srgb, var(--pd-fb-glow-300) 15%, transparent)',
  '--pd-color-border-outline': 'color-mix(in srgb, var(--pd-fb-glow-300) 28%, transparent)',
  '--pd-color-border-interactive': 'color-mix(in srgb, var(--pd-fb-glow-300) 50%, transparent)',
  '--pd-color-border-interactive-active': 'var(--pd-fb-glow-300)',
  '--pd-color-border-inverse': 'var(--pd-fb-night-950)',
  '--pd-color-border-focus': 'var(--pd-fb-glow-300)',
  '--pd-color-border-danger': 'var(--pd-fb-danger-dark)',
  '--pd-color-feedback-info': 'var(--pd-fb-glow-300)',
  '--pd-color-feedback-success': 'var(--pd-fb-glow-300)',
  '--pd-color-feedback-warning': 'var(--pd-fb-amber-dark)',
  '--pd-color-feedback-danger': 'var(--pd-fb-danger-dark)',
  '--pd-color-action-primary': 'var(--pd-fb-glow-300)',
  '--pd-color-action-primary-hover': 'var(--pd-fb-glow-500)',
  '--pd-color-action-primary-pressed': 'var(--pd-fb-glow-700)',
  '--pd-color-action-secondary': 'var(--pd-fb-night-800)',
  '--pd-color-action-secondary-hover': 'var(--pd-fb-night-700)',
  '--pd-color-action-secondary-pressed': 'var(--pd-fb-night-500)',
  '--pd-color-action-ghost-hover': 'color-mix(in srgb, var(--pd-fb-glow-300) 10%, transparent)',
  '--pd-color-action-ghost-pressed': 'color-mix(in srgb, var(--pd-fb-glow-300) 18%, transparent)',
  '--pd-color-action-disabled': 'var(--pd-fb-night-600)',
  '--pd-color-focus-ring': 'color-mix(in srgb, var(--pd-fb-glow-300) 80%, transparent)',
  '--pd-color-focus-ring-offset': 'var(--pd-fb-night-950)',
  '--pd-fb-night-500': '#1e4020',
  '--pd-fb-night-600': '#1a3a1a',
  '--pd-fb-night-700': '#2a5a2a',
  '--pd-fb-night-800': '#102830',
  '--pd-fb-night-900': '#0d2028',
  '--pd-fb-night-950': '#0a1a1f',
  '--pd-fb-glow-300': '#c8e6a0',
  '--pd-fb-glow-500': '#a0c878',
  '--pd-fb-glow-700': '#78a050',
  '--pd-fb-text-50': '#d0f0d8',
  '--pd-fb-text-200': '#a8d4b0',
  '--pd-fb-text-muted': '#6a9870',
  '--pd-fb-danger-dark': '#ff7a5a',
  '--pd-fb-danger-bg-dark': '#b03a1a',
  '--pd-fb-amber-dark': '#ffd080',
  '--pd-fb-smash-text': '#c8e6a0',
  '--pd-fb-smash-hint': '#a0c878',
  '--pd-fb-smash-grad-start': '#0a2a12',
  '--pd-fb-smash-grad-end': '#051a0a',
  '--pd-color-background-default': 'var(--pd-fb-night-950)',
  '--pd-color-background-elevated': 'var(--pd-fb-night-800)',
  '--pd-color-background-hover': 'var(--pd-fb-night-700)',
  '--pd-color-text-muted': 'var(--pd-fb-text-muted)',
  '--pd-color-accent-default': 'var(--pd-fb-glow-300)',
  '--pd-color-accent-hover': 'var(--pd-fb-glow-500)',
  '--pd-color-accent-subtle': 'color-mix(in srgb, var(--pd-fb-glow-300) 12%, transparent)',
  '--pd-color-accent-filled': 'var(--pd-fb-glow-300)',
  '--pd-color-accent-text': 'var(--pd-fb-night-950)',
  '--pd-color-shadow-default': 'color-mix(in srgb, var(--pd-fb-glow-300) 15%, transparent)',
  '--pd-color-semantic-success': 'var(--pd-fb-glow-300)',
  '--pd-color-semantic-danger': 'var(--pd-fb-danger-bg-dark)',
  '--pd-color-semantic-warning': 'var(--pd-fb-amber-dark)',
  '--pd-color-smash-border': 'var(--pd-fb-glow-300)',
  '--pd-color-smash-text': 'var(--pd-fb-smash-text)',
  '--pd-color-smash-hint': 'var(--pd-fb-smash-hint)',
  '--pd-color-overlay-backdrop': 'color-mix(in srgb, var(--pd-fb-night-950) 85%, transparent)',
  '--pd-effect-particle-1': '#c8e6a0',
  '--pd-effect-particle-2': '#4aaa4a',
  '--pd-effect-particle-3': '#f0ff80',
  '--pd-effect-particle-4': '#78a050',
};
