/**
 * AUTO-GENERATED — do not edit by hand.
 * Source of truth: design-tokens/*.json (Tokens Studio format).
 * Regenerate with `npm run tokens:build`.
 */

export const light: Record<string, string> = {
  '--pd-color-surface-page': 'var(--pd-lavender-50)',
  '--pd-color-surface-page-alt': 'var(--pd-lavender-100)',
  '--pd-color-surface-primary': 'var(--pd-lavender-200)',
  '--pd-color-surface-secondary': 'var(--pd-lavender-50)',
  '--pd-color-surface-raised': 'var(--pd-white)',
  '--pd-color-surface-overlay': 'color-mix(in srgb, var(--pd-violet-900) 65%, transparent)',
  '--pd-color-surface-inverse': 'var(--pd-violet-900)',
  '--pd-color-surface-disabled': 'var(--pd-lavender-300)',
  '--pd-color-text-primary': 'var(--pd-violet-900)',
  '--pd-color-text-secondary': 'var(--pd-violet-700)',
  '--pd-color-text-tertiary': 'var(--pd-violet-600)',
  '--pd-color-text-inverse': 'var(--pd-lavender-50)',
  '--pd-color-text-disabled': 'var(--pd-violet-600)',
  '--pd-color-text-accent': 'var(--pd-teal-500)',
  '--pd-color-text-success': 'var(--pd-sw-success-light)',
  '--pd-color-text-warning': 'var(--pd-sw-amber-light)',
  '--pd-color-text-danger': 'var(--pd-sw-danger-light)',
  '--pd-color-border-outline-variant': 'color-mix(in srgb, var(--pd-magenta-700) 20%, transparent)',
  '--pd-color-border-outline': 'color-mix(in srgb, var(--pd-magenta-700) 40%, transparent)',
  '--pd-color-border-interactive': 'var(--pd-magenta-700)',
  '--pd-color-border-interactive-active': 'var(--pd-magenta-500)',
  '--pd-color-border-inverse': 'var(--pd-lavender-50)',
  '--pd-color-border-focus': 'var(--pd-teal-500)',
  '--pd-color-border-danger': 'var(--pd-sw-danger-light)',
  '--pd-color-feedback-info': 'var(--pd-teal-500)',
  '--pd-color-feedback-success': 'var(--pd-sw-success-light)',
  '--pd-color-feedback-warning': 'var(--pd-sw-amber-light)',
  '--pd-color-feedback-danger': 'var(--pd-sw-danger-light)',
  '--pd-color-action-primary': 'var(--pd-teal-500)',
  '--pd-color-action-primary-hover': 'var(--pd-teal-700)',
  '--pd-color-action-primary-pressed': 'var(--pd-teal-900)',
  '--pd-color-action-secondary': 'var(--pd-lavender-200)',
  '--pd-color-action-secondary-hover': 'var(--pd-lavender-300)',
  '--pd-color-action-secondary-pressed': 'var(--pd-lavender-400)',
  '--pd-color-action-ghost-hover': 'color-mix(in srgb, var(--pd-magenta-700) 10%, transparent)',
  '--pd-color-action-ghost-pressed': 'color-mix(in srgb, var(--pd-magenta-700) 20%, transparent)',
  '--pd-color-action-disabled': 'var(--pd-lavender-500)',
  '--pd-color-focus-ring': 'color-mix(in srgb, var(--pd-teal-500) 80%, transparent)',
  '--pd-color-focus-ring-offset': 'var(--pd-lavender-50)',
  '--pd-sw-danger-light': '#cc0033',
  '--pd-sw-success-light': '#006644',
  '--pd-sw-success-light-hover': '#004422',
  '--pd-sw-amber-light': '#996600',
  '--pd-sw-smash-text-light': '#8800aa',
  '--pd-sw-smash-hint-light': '#aa44aa',
  '--pd-sw-smash-grad-start-light': '#f0e6ff',
  '--pd-sw-smash-grad-end-light': '#e0d0ff',
  '--pd-color-background-default': 'var(--pd-lavender-50)',
  '--pd-color-background-elevated': 'var(--pd-lavender-200)',
  '--pd-color-background-hover': 'var(--pd-lavender-300)',
  '--pd-color-text-primary': 'var(--pd-violet-900)',
  '--pd-color-text-secondary': 'var(--pd-violet-700)',
  '--pd-color-text-muted': 'var(--pd-violet-600)',
  '--pd-color-accent-default': 'var(--pd-teal-500)',
  '--pd-color-accent-hover': 'var(--pd-teal-700)',
  '--pd-color-accent-subtle': 'color-mix(in srgb, var(--pd-teal-500) 12%, transparent)',
  '--pd-color-accent-filled': 'var(--pd-teal-500)',
  '--pd-color-accent-text': 'var(--pd-white)',
  '--pd-color-shadow-default': 'color-mix(in srgb, var(--pd-magenta-700) 25%, transparent)',
  '--pd-color-semantic-success': 'var(--pd-sw-success-light)',
  '--pd-color-semantic-danger': 'var(--pd-sw-danger-light)',
  '--pd-color-semantic-warning': 'var(--pd-sw-amber-light)',
  '--pd-color-smash-border': 'var(--pd-magenta-700)',
  '--pd-color-smash-text': 'var(--pd-sw-smash-text-light)',
  '--pd-color-smash-hint': 'var(--pd-sw-smash-hint-light)',
  '--pd-color-focus-ring': 'color-mix(in srgb, var(--pd-teal-500) 80%, transparent)',
  '--pd-color-overlay-backdrop': 'color-mix(in srgb, var(--pd-violet-900) 60%, transparent)',
  '--pd-font-brand': '\'Orbitron\', \'Courier New\', monospace',
  '--pd-font-brand-ja': '\'Orbitron\', \'Courier New\', monospace',
  '--pd-font-body': '\'Share Tech Mono\', \'Courier New\', monospace',
  '--pd-effect-particle-1': '#007a78',
  '--pd-effect-particle-2': '#5a3a9a',
  '--pd-effect-particle-3': '#ff2dff',
  '--pd-effect-particle-4': '#d97706',
};

export const dark: Record<string, string> = {
  '--pd-color-surface-page': 'var(--pd-sw-navy-950)',
  '--pd-color-surface-page-alt': 'var(--pd-sw-navy-900)',
  '--pd-color-surface-primary': 'var(--pd-sw-navy-800)',
  '--pd-color-surface-secondary': 'var(--pd-sw-navy-950)',
  '--pd-color-surface-raised': 'var(--pd-sw-navy-700)',
  '--pd-color-surface-overlay': 'color-mix(in srgb, var(--pd-sw-navy-950) 88%, transparent)',
  '--pd-color-surface-inverse': 'var(--pd-sw-purple-text-50)',
  '--pd-color-surface-disabled': 'var(--pd-sw-navy-600)',
  '--pd-color-text-primary': 'var(--pd-sw-purple-text-50)',
  '--pd-color-text-secondary': 'var(--pd-purple-300)',
  '--pd-color-text-tertiary': 'var(--pd-sw-purple-muted)',
  '--pd-color-text-inverse': 'var(--pd-sw-navy-950)',
  '--pd-color-text-disabled': 'var(--pd-sw-purple-muted)',
  '--pd-color-text-accent': 'var(--pd-sw-neon-cyan-300)',
  '--pd-color-text-success': 'var(--pd-sw-neon-green-300)',
  '--pd-color-text-warning': 'var(--pd-sw-amber-500)',
  '--pd-color-text-danger': 'var(--pd-sw-hot-red-300)',
  '--pd-color-border-outline-variant': 'color-mix(in srgb, var(--pd-sw-chrome) 22%, transparent)',
  '--pd-color-border-outline': 'color-mix(in srgb, var(--pd-sw-chrome) 34%, transparent)',
  '--pd-color-border-interactive': 'color-mix(in srgb, var(--pd-sw-chrome) 55%, transparent)',
  '--pd-color-border-interactive-active': 'var(--pd-sw-chrome)',
  '--pd-color-border-inverse': 'var(--pd-sw-navy-950)',
  '--pd-color-border-focus': 'var(--pd-sw-neon-cyan-300)',
  '--pd-color-border-danger': 'var(--pd-sw-hot-red-300)',
  '--pd-color-feedback-info': 'var(--pd-sw-neon-cyan-300)',
  '--pd-color-feedback-success': 'var(--pd-sw-neon-green-300)',
  '--pd-color-feedback-warning': 'var(--pd-sw-amber-500)',
  '--pd-color-feedback-danger': 'var(--pd-sw-hot-red-300)',
  '--pd-color-action-primary': 'var(--pd-sw-neon-cyan-300)',
  '--pd-color-action-primary-hover': 'var(--pd-sw-neon-cyan-500)',
  '--pd-color-action-primary-pressed': 'var(--pd-sw-neon-cyan-700)',
  '--pd-color-action-secondary': 'var(--pd-sw-navy-800)',
  '--pd-color-action-secondary-hover': 'var(--pd-sw-navy-700)',
  '--pd-color-action-secondary-pressed': 'var(--pd-sw-navy-500)',
  '--pd-color-action-ghost-hover': 'color-mix(in srgb, var(--pd-sw-chrome) 10%, transparent)',
  '--pd-color-action-ghost-pressed': 'color-mix(in srgb, var(--pd-sw-chrome) 18%, transparent)',
  '--pd-color-action-disabled': 'var(--pd-sw-navy-600)',
  '--pd-color-focus-ring': 'color-mix(in srgb, var(--pd-sw-neon-cyan-300) 80%, transparent)',
  '--pd-color-focus-ring-offset': 'var(--pd-sw-navy-950)',
  '--pd-sw-navy-500': '#24247a',
  '--pd-sw-navy-600': '#1e1e5a',
  '--pd-sw-navy-700': '#1a1a50',
  '--pd-sw-navy-800': '#10103a',
  '--pd-sw-navy-900': '#0a0a22',
  '--pd-sw-navy-950': '#07071a',
  '--pd-sw-neon-cyan-300': '#00fff0',
  '--pd-sw-neon-cyan-500': '#00ccc8',
  '--pd-sw-neon-cyan-700': '#009e9b',
  '--pd-sw-neon-green-300': '#00ff88',
  '--pd-sw-neon-green-500': '#00cc66',
  '--pd-sw-hot-red-300': '#ff2d55',
  '--pd-sw-hot-red-500': '#d01843',
  '--pd-sw-amber-500': '#ffb800',
  '--pd-sw-purple-text-50': '#eeddff',
  '--pd-sw-purple-muted': '#9070c0',
  '--pd-sw-chrome': 'var(--pd-sw-purple-muted)',
  '--pd-sw-smash-text': '#dd00dd',
  '--pd-sw-smash-hint': '#cc44cc',
  '--pd-sw-smash-grad-start': '#1a004a',
  '--pd-sw-smash-grad-end': '#000a3a',
  '--pd-color-background-default': 'var(--pd-sw-navy-950)',
  '--pd-color-background-elevated': 'var(--pd-sw-navy-800)',
  '--pd-color-background-hover': 'var(--pd-sw-navy-700)',
  '--pd-color-text-primary': 'var(--pd-sw-purple-text-50)',
  '--pd-color-text-secondary': 'var(--pd-purple-300)',
  '--pd-color-text-muted': 'var(--pd-sw-purple-muted)',
  '--pd-color-accent-default': 'var(--pd-sw-neon-cyan-300)',
  '--pd-color-accent-hover': 'var(--pd-sw-neon-cyan-500)',
  '--pd-color-accent-subtle': 'color-mix(in srgb, var(--pd-sw-neon-cyan-300) 12%, transparent)',
  '--pd-color-accent-filled': 'var(--pd-sw-neon-cyan-300)',
  '--pd-color-accent-text': 'var(--pd-sw-navy-950)',
  '--pd-color-shadow-default': 'color-mix(in srgb, var(--pd-sw-chrome) 18%, transparent)',
  '--pd-color-semantic-success': 'var(--pd-sw-neon-green-300)',
  '--pd-color-semantic-danger': 'var(--pd-sw-hot-red-500)',
  '--pd-color-semantic-warning': 'var(--pd-sw-amber-500)',
  '--pd-color-smash-border': 'var(--pd-sw-chrome)',
  '--pd-color-smash-text': 'var(--pd-sw-smash-text)',
  '--pd-color-smash-hint': 'var(--pd-sw-smash-hint)',
  '--pd-color-focus-ring': 'color-mix(in srgb, var(--pd-sw-neon-cyan-300) 80%, transparent)',
  '--pd-color-overlay-backdrop': 'color-mix(in srgb, var(--pd-sw-navy-950) 85%, transparent)',
  '--pd-font-brand': '\'Orbitron\', \'Courier New\', monospace',
  '--pd-font-brand-ja': '\'Orbitron\', \'Courier New\', monospace',
  '--pd-font-body': '\'Share Tech Mono\', \'Courier New\', monospace',
  '--pd-effect-particle-1': '#00fff0',
  '--pd-effect-particle-2': '#00ff88',
  '--pd-effect-particle-3': '#ff2d55',
  '--pd-effect-particle-4': '#ffb800',
};
